# Generated by Django 2.2.7 on 2022-02-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_date', models.DateField()),
                ('credit_agency', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('credit_service_date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('voided', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('voided', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('debt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.Credit')),
            ],
        ),
    ]
