# Generated by Django 2.2.7 on 2022-12-11 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate_date', models.DateField()),
                ('allocate_amount', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('voided', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_date', models.DateField()),
                ('chart_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=64)),
                ('perc', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('voided', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_date', models.DateField()),
                ('allocated_amount', models.IntegerField(default=0)),
                ('voided', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('allocate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributer.Allocate')),
                ('chart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributer.Chart')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('transfer_amount', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('voided', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('transact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributer.Transact')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
