# Generated by Django 2.2.7 on 2023-02-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transact',
            name='transact_allocation',
            field=models.IntegerField(default=0),
        ),
    ]
