from django.urls import path
from . import views
urlpatterns = [
    path("tawala/",views.TawalaView.as_view(),name="tawala"),
    path("",views.DailyListView.as_view(),name="index"),
    path('index/',views.index,name="index"),
    path("categories/",views.CategoryListView.as_view(),name="category_list"),
    path("addCategory/",views.CategoryView.as_view(),name="add_category"),
    path("deletecategory/<int:id>",views.DeleteCategoryView.as_view(),name="delete_category"),
    path('addspent/',views.AddSpentView.as_view(),name='add_spent'),
    path('dailylist/',views.DailyListView.as_view(),name='daily_list'),
    path('monthlylist/',views.MonthlyListView.as_view(),name='monthly_list'),
    path('spentday/<str:day>',views.SpentInASpecificDayView.as_view(),name='specific_day'),
    path('updatecategory/<int:id>',views.UpdateCategoryView.as_view(),name='update_category'),
    path('updatespent/<int:id>',views.UpdateSpentView.as_view(),name="update_spent"),
    path('deletebunch/<str:day>',views.DeleteBunchView.as_view(),name="delete_bunch"),
    path('deletespent/<int:id>',views.DeleteSpentView.as_view(),name='delete_spent'),
    path('savingslist/',views.SavingsList.as_view(),name="savings_list"),
    path('createtracking/',views.CreateTrackingView.as_view(),name="create_tracking"),
    path('createtrack/',views.CreateTrackView.as_view(),name="create_track"),
    path('updatetrack/<int:pk>',views.UpdateTrackView.as_view(),name="update_track"),
    path('tracklist/',views.TrackListView.as_view(),name="track_list"),
    path('trackinglist/',views.TrackingListView.as_view(),name="tracking_list"),
    path('trackerlist/<int:pk>',views.TrackerListView.as_view(),name="tracker_list"),
    path('allspents/',views.AllListView.as_view(),name="all_spents"),
    path('trackspents/<int:pk>',views.TrackerSpentListView.as_view(),name="track_spents"),
    path('summarygraph/<int:track>',views.SummaryGraphView.as_view(),name="summary_graph"),
    path('addbudgetcategory/',views.BudgetCategoryView.as_view(),name="add_budget_category"),
    path('updatebudgetcategory/<int:id>',views.UpdateBudgetCategoryView.as_view(),name="update_budget_category"),
    path('budgetcategorylist/',views.BudgetCategoryListView.as_view(),name="budget_category_list"),
    path('deletebudgetcategory/<int:id>',views.DeleteBudgetCategoryView.as_view(),name="delete_budget_category"),
    path('addbudget/',views.AddBudgetView.as_view(),name="add_budget"),
    path('updatebudget/<int:id>',views.UpdateBudgetView.as_view(),name="update_budget"),
    path('deletebudget/<int:id>',views.DeleteBudgetView.as_view(),name="delete_budget"),
    path('budgetlist',views.BudgetListView.as_view(),name='budget_list'),
    path('budgetview/<int:budget>',views.IndividualBudgetView.as_view(),name="budget_view"),
    path('addclassitem',views.AddBudgetClassItemView.as_view(),name='add_class_item'),
    path('updateclassitem/<int:id>',views.UpdateBudgetClassItemView.as_view(),name='update_class_item'),
    path('deleteclassitem/<int:id>',views.DeleteBudgetClassItemView.as_view(),name='delete_class_item'),
    path('classitemlist/',views.BudgetClassItemListView.as_view(),name='class_item_list'),
    path('addbudgetitem/',views.AddBudgetItemView.as_view(),name='add_budget_item'),
    path('updatebudgetitem/<int:id>',views.UpdateBudgetItemView.as_view(),name='update_budget_item'),
    path('deletebudgetitem/<int:id>',views.DeleteBudgetItemView.as_view(),name='delete_budget_item'),
    path('budgetitemlist/',views.BudgetItemListView.as_view(),name='budget_item_list'),
    path('periodsummarygraph/',views.PeriodSummaryGraphView.as_view(),name='period_graph'),
    path('budgetestimate/',views.BudgetEstimationView.as_view(),name='budget_estimate'),
    path('singleselection/<str:start_date>/<str:end_date>/<str:category>/',views.PeriodIndividualView.as_view(),name='single_selection'),
    path('categoryselection/<str:start_date>/<str:end_date>/<str:category>/',views.CategoryIndividualView.as_view(),name='category_selection'),
    path('amortizedbudgetestimate/',views.AmortizedBudgetEstimatesView.as_view(),name='amortized'),
    path('budgetperformance/',views.BudgetPerformanceView.as_view(),name='budget_performance'),
    path('weeklyanalysis/',views.WeeklyAnalysisView.as_view(),name='weekly_analysis'),
    path('weeklysavings/',views.WeeklyBudgetSavingsView.as_view(),name='weekly_savings'),
    path('createsavingstracking/',views.CreateSavingsTrackingView.as_view(),name="create_savings_tracking"),
    path('updateweeksurplus/',views.UpdateWeeklySurplusView.as_view(),name="update_week_surplus"),





]
