# Generated by Django 2.2.7 on 2022-02-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='savingstracker',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='spent',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-start_date']},
        ),
    ]
