# Generated by Django 2.2.7 on 2023-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0003_auto_20220324_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
