# Generated by Django 2.2.7 on 2023-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0005_category_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
