# Generated by Django 2.2.7 on 2023-06-27 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spent', '0006_auto_20230423_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.Budget')),
                ('budget_class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.BudgetClassItem')),
                ('budgetitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.BudgetItem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
