# Generated by Django 2.2.7 on 2023-08-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0007_budgetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlog',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
