# Generated by Django 2.2.7 on 2023-09-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0008_budgetlog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='daily_limit',
            field=models.IntegerField(default=0),
        ),
    ]
