# Generated by Django 4.0.6 on 2024-11-21 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spent', '0009_track_daily_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySavingsTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voided', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.budgetclassitem')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.track')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpentWeekBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('budget_amount', models.FloatField(blank=True, null=True)),
                ('budget_spent_start', models.FloatField(blank=True, null=True)),
                ('week_budget', models.FloatField(blank=True, null=True)),
                ('week_spent', models.FloatField(blank=True, null=True)),
                ('week_remaining', models.FloatField(blank=True, null=True)),
                ('bf', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('amount_bf', models.FloatField(blank=True, null=True)),
                ('amount_saved', models.FloatField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('voided', models.BooleanField(default=False)),
                ('budget_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.budgetclassitem')),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spent.budget')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spent_week_budget',
            },
        ),
    ]
