# Generated by Django 2.2.7 on 2024-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='task_item_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
